name: Feature request
description: Request a feature request for `@RimacTechnology/style-guide`
labels: [Feature]
body:
    - type: checkboxes
      id: issue-prerequisite
      attributes:
          label: Issues
          options:
              - label:
                    I have checked [existing issues](https://github.com/RimacTechnology/style-guide/issues) and there are no
                    existing ones with the same request.
                required: true

    - type: textarea
      attributes:
          label: 'Feature description'
      validations:
          required: true
