on:
    push:
        branches:
            - master
            - beta
            - alpha
    pull_request:
    workflow_dispatch:

env:
    HUSKY: 0

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: yarn
            - run: yarn install
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: yarn lint
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: yarn
            - run: yarn install
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: yarn test
    release:
        name: Release
        needs: [lint, test]
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: yarn
            - run: yarn install
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: yarn release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
